version: "3"
services:
  db:
    image: oscarfonts/h2
    container_name: zeebe_db
    ports:
      - "1521:1521"
      - "81:81"
  monitor:
    image: camunda/zeebe-simple-monitor
    environment:
      - spring.datasource.url=jdbc:h2:tcp://db:1521/zeebe-monitor
      - io.zeebe.monitor.connectionString=app:26500
    ports:
    - "8080:8080"
  app:
    image: camunda/zeebe
    environment:
    - ZEEBE_LOG_LEVEL=debug
    volumes:
      - ./zeebe-simple-monitor-exporter-0.10.0.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter.jar
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    ports:
    - "26500:26500"
    - "26501:26501"
    - "26502:26502"
    - "26503:26503"
    - "26504:26504"